# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  push

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Prepare version
      run: |
        # get release version
        VERSION=$(echo $GITHUB_REF | sed 's#.*/v##')

        # file and content that will be replaced
        PLACEHOLDER="version='default'"
        SETUP_FILE="setup.py"

        # check to see that content is in file, then replace to have latest release version
        grep "${PLACEHOLDER}" "${SETUP_FILE}"
        sed -i "s/$PLACEHOLDER/version='${VERSION}'/g" ${SETUP_FILE}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine sphinx sphinx_rtd_theme
        pip install -r requirements.txt
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        ls
    -
      name: Update Documentation
      run: |
        cd docs
        make html
        pwd
        cd ..
        pwd
        echo "in here before commit"
        git add .
        echo "in here before commit"
        git commit -m "update operator csv libs documentation"
        git push origin master