name: Update Python Documentation

on:
  release:
    types: [created]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    -
      name: Update Documentation
      run: |
        make --directory docs/ html
        git config user.email "evelio.sosa@ibm.com"
        git config user.name "Evelio Sosa"
        git add .
        git commit -m "update operator csv libs documentation" || true